docs/clients/java.md

Hi guys,
I have added the java SDK documentation (including default values).
Cheers,
Olga

Added caching documentation for the java SDK

---

docs/clients/java.md

Hi @dabeeeenster 
I updated the documentation as suggested in this issue: https://github.com/Flagsmith/flagsmith-java-client/issues/35.
Cheers,
Olga

Updated docs according to user feedback

---

docs/clients/java.md

Adds new documentation around usage of `identifyUserwithTraits` method.

New docs on response to identifyUserwithTraits

---

docs/clients/java.md

Update Java SDK caching documentation to reflect new caching functionality.

Update Java SDK caching documentation

---

docs/clients/client-side/flutter.md

* updating initialization
* adding streams
* adding reset feature

refac: update documentation

---

docs/deployment/kubernetes.md

Docs for https://github.com/Flagsmith/flagsmith-charts/pull/55

Docs for flagsmith-charts PR 55

---

docs/clients/3rd-party.md

Hey, I've developed a Flagsmith Vue Client, it would be great if we add it to the docs, thanks!

Add flagsmith-vue-client

---

docs/deployment/kubernetes.md

Docs for https://github.com/Flagsmith/flagsmith-charts/pull/56

Docs for flagsmith-charts PR 56

---

docs/clients/client-side/ios.md

See https://github.com/Flagsmith/flagsmith-ios-client/pull/14 for details.

Updated documentation to include Swift Concurrent example. (#59)

---

docs/deployment/kubernetes.md

Docs for https://github.com/Flagsmith/flagsmith-charts/pull/75

Docs for flagsmith-charts PR 75

---

docs/clients/server-side.md

Fix a number of errors in the C# docs

Fix csharp docs

---

docs/clients/server-side.md

- Correct elixir version on docs
- Nitpicks on urls description
I think this is all that is needed

Correct elixir version on docs

---

docs/clients/client-side/javascript.md
docs/clients/client-side/react.md

Described differences between flagsmith and react-native-flagsmith, added information about flagsmith-es.

Add information around React Native and flagsmith-es

---

docs/clients/client-side/nextjs-and-ssr.md
docs/clients/client-side/react.md
versioned_docs/version-v1.0/clients/client-side/nextjs-and-ssr.md
versioned_docs/version-v1.0/clients/client-side/react.md

I just changed few localhost links that were broken.
Thank you 👍🏽

Change localhost to docs url

---

docs/clients/client-side/javascript.md
docs/clients/client-side/nextjs-and-ssr.md

Improved the NextJS middleware example to use flag enabled state and remote config

Improve middleware example

---

docs/deployment/locally-api.md

Add documentation for statsd usage.

Add statsd documentation

---

docs/advanced-use/edge-api.md

Following and during added

---

docs/deployment/task-processor.md

Minor tweaks to task processor documentation.

Update task processor documentation

---

docs/deployment/kubernetes.md

Add statsd documentation for kubernetes

WIP: Add statsd information to k8s docs

---

docs/basic-features/managing-segments.md
docs/deployment/overview.md

Updating documentation for add modulo operator issue. [Link](https://github.com/Flagsmith/flagsmith/issues/403)

Feat/GitHub-403 Add modulo operator for segment rule

---

docs/deployment/locally-api.md

Add documentation to detail configuration options for caching flags and identities endpoints.

Add documentation for caching flags and identities endpoints

---

docs/deployment/locally-api.md

Fix table escaping

---

docs/clients/server-side.md

* Update Java initialisation options
* Add note to local evaluation to confirm that user overrides don't work

Update java docs & add note to local evaluation

---

api_spec/edge_api.json

bulk-identities endpoint added

bulk-identities endpoint added

---

api_spec/edge_api.json

Add docs for PUT method on bulk-identities endpoint

Add PUT endpoint docs

---

docs/deployment/locally-api.md

Add documentation for configuring database replication.

Add docs on DB replication

---

docs/deployment/overview.md

Add is set and is not set operators to segment_operators config value for Flagsmith on Flagsmith setup.

ADd is set / is not set

---

docs/deployment/enterprise-edition.md

LDAP functionality is only available in our EE image. Correct the documentation.

LDAP functionality is EE only

---

docs/clients/server-side.md

Add proxies argument to python configuration documentation.

Add proxies argument to python configuration

---

package-lock.json
package.json

Improvement/docusaurus 2.3.1

---

docs/platform/releases.md

Bring release notes up to date

---

docs/integrations/overview.md
versioned_docs/version-v1.0/integrations/overview.md

Add Slack to integrations overview page.

Add slack to overview

---

docs/deployment/hosting/locally-api.md

Added the `FLAGSMITH_DOMAIN` environment variable.
*WARNING*: To be merged after the actual setting is released ([PR](https://github.com/Flagsmith/flagsmith/pull/2120)).

Add FLAGSMITH_DOMAIN environment variable
